const ENUM = {
  PLACE: {
    LIVING_ROOM: "living_room",
    BEDROOM: "bedroom",
    GARDEN: "garden",
    KITCHEN: "kitchen",
    CELLAR: "cellar",
    TOILET: "toilet",
    BALCONY: "balcony"
  },
  ROLE: {
    HIGH_SCHOOL_STUDENT: "high_school_student",
    MANAGER: "manager",
    FORENSIC_DOCTOR: "forensic_doctor",
    GUIDE: "guide",
    PROPSMAN: "propsman",
    COACH: "coach",
    POLICE_WOMAN: "police_woman",
    HUNTER: "hunter",
    CONJURATOR: "conjurator",
    MALE_TOURIST: "male_tourist",
    FEMALE_TOURIST: "female_tourist",
    MALE_DOCTOR: "male_doctor",
    FEMALE_DOCTOR: "female_doctor",
    MISTERIOUS_MAN: "misterious_man",
    STUDENT: "student",
    DETECTIVE: "detective",
    SOLDIER: "soldier",
    PROGRAMMER: "programmer"
  },
  SKILL: {
    HIGH_SCHOOL_STUDENT_DEXTEROUS: "dexterous",
    FEMALE_DOCTOR_PERFUME: "perfume",
    FEMALE_DOCTOR_MIND_IMPLY_1: "mind_imply_1",
    FEMALE_DOCTOR_MIND_IMPLY_2: "mind_imply_2",
    MALE_DOCTOR_BRAIN_DIAGNOSIS: "brain_diagnosis",
    FORENSIC_DOCTOR_CRIMINAL_INVEST: "criminal_invest",
    FEMALE_TOURIST_EXPLORATION: "exploration",
    FEMALE_TOURIST_INVITATION: "invitation",
    MALE_TOURIST_SPECIAL_TRAP: "special_trap",
    MALE_TOURIST_METICULOUS: "meticulous",
    HUNTER_STRUGGLE: "struggle",
    COACH_INSPIRE: "inspire",
    GUIDE_PERFECT_MEMORY: "perfect_memory",
    GUIDE_SAFE_CHECK: "safe_check",
    SOLDIER_PROTECTION: "protection",
    SOLDIER_SUPPRESS: "suppress",
    POLICE_WOMAN_SUSPICION: "suspicion",
    POLICE_WOMAN_GUARD: "guard",
    CONJURATOR_MEDIUMSHIP: "mediumship",
    CONJURATOR_WHITSUNDAYS: "whitsundays",
    PROPSMAN_PROPSBOX: "propsbox",
    PROPSMAN_SHOW_MECHANISM: "show_mechanism",
    PROPSMAN_SHOW_TOY_CAR: "show_toy_car",
    PROPSMAN_SHOW_FRIGHTEN: "show_frighten",
    PROPSMAN_SHOW_DOLL: "show_doll",
    MANAGER_HOST_ADVANTAGE_1: "host_advantage_1",
    MANAGER_HOST_ADVANTAGE_2: "host_advantage_2",
    MANAGER_ESCAPE: "escape",
    STUDENT_NIGHTMARE: "nightmare",
    STUDENT_USELESS: "useless",
    DETECTIVE_DETECTIVE: "detective",
    DETECTIVE_CRIME_GENIUS_1: "crime_genius_1",
    DETECTIVE_CRIME_GENIUS_2: "crime_genius_2",
    DETECTIVE_LEAD_ADVANTAGE: "lead_advantage",
    MISTERIOUS_MAN_EXPERT_1: "expert_1",
    MISTERIOUS_MAN_EXPERT_2: "expert_2",
    PROGRAMMER_OVERTIME: "overtime",
    PROGRAMMER_OVERSTRAIN: "overstrain",
    PROGRAMMER_CONSTANCY: "constancy"
  }
};

export default ENUM;
